[package]
name = "sdkwork-api-sandbox-assembly"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-sandbox application HTTP plane."

[lints]
workspace = true

[lib]
name = "sdkwork_api_sandbox_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
sdkwork-web-contract.workspace = true
sqlx.workspace = true
thiserror.workspace = true
sdkwork-database-sqlx = { workspace = true }
sdkwork-intelligence-sandbox-repository-sqlx = { workspace = true }
sdkwork-intelligence-sandbox-service = { workspace = true }
sdkwork-sandbox-database-host = { workspace = true }
sdkwork-routes-sandbox-app-api.workspace = true
sdkwork-routes-sandbox-internal-api.workspace = true
